version: '3.7'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  single-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: single-elastic
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    environment:
      - ELASTICSEARCH_HOSTS=http://single-elastic:9200
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 5601:5601
    depends_on:
      - single-elastic

volumes:
  elasticsearch-data:
    driver: local

