-- sql_last_value는 numeric, timestamp 데이터만 비교 가능하다.
SELECT CAR.*
FROM (SELECT TO_TIMESTAMP(V_UPDATE_DTM, 'YYYYMMDDHH24MISS') AS TS_UPDATE_DTM,
             CAR.*
      FROM VEHICLE_CAR CAR) CAR
WHERE CAR.UPDATE_DTM <= TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')
  AND :sql_last_value < TS_UPDATE_DTM
ORDER BY CAR.UPDATE_DTM
