logging:
  level:
    root: warn
    org.xpdojo: debug
    org.springframework:
      web: debug
      data:
        elasticsearch:
          core: debug
          client.WIRE: trace
    org.elasticsearch: debug
