# https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4
# http://honeymon.io/tech/2021/01/16/spring-boot-config-data-migration.html
spring:
  profiles:
    active: dev

---
spring:
  profiles.group:
      public:
        - dev
        - debug
        - es-dev

---
spring:
  profiles.group:
      dev:
        - dev
        - debug
        - elastic-prod

---
spring:
  profiles.group:
      prod:
        - prod
        - info
        - elastic-prod
