# https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4
# http://honeymon.io/tech/2021/01/16/spring-boot-config-data-migration.html
# https://docs.spring.io/spring-boot/docs/2.7.4/gradle-plugin/reference/htmlsingle/#running-your-application.passing-arguments
#spring:
#  profiles:
#    active: dev

---
spring:
  profiles.group:
      local:
        - dev
        - debug
        - elastic-dev

---
spring:
  profiles.group:
      dev:
        - dev
        - debug
        - elastic-dev

---
spring:
  profiles.group:
      prod:
        - prod
        - info
        - elastic-prod
